# Generated by Django 3.1.4 on 2020-12-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warn',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='warn',
            old_name='vote',
            new_name='upvote',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
