# Generated by Django 3.1.4 on 2020-12-04 02:00

from django.db import migrations, models
import warns.models


class Migration(migrations.Migration):

    dependencies = [
        ('warns', '0002_auto_20201204_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.ImageField(null=True, upload_to=warns.models.comment_photo_path),
        ),
    ]
