# Generated by Django 3.1.4 on 2020-12-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warns', '0003_auto_20201204_0200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warn',
            options={},
        ),
        migrations.AlterField(
            model_name='warn',
            name='time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
