# Generated by Django 3.1.4 on 2020-12-05 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warns', '0004_auto_20201205_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='warn',
            name='devoters',
            field=models.ManyToManyField(related_name='devoted_warnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warn',
            name='upvoters',
            field=models.ManyToManyField(related_name='upvoted_warnings', to=settings.AUTH_USER_MODEL),
        ),
    ]
