# Generated by Django 3.1.4 on 2020-12-08 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warns', '0005_auto_20201205_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='src',
        ),
    ]
