# Generated by Django 3.1.4 on 2020-12-04 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='credit_vote',
            new_name='credit_upvote',
        ),
    ]
