# Generated by Django 3.1.4 on 2020-12-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='level',
            field=models.CharField(choices=[('E', 'Extreme'), ('D', 'Dangerous'), ('N', 'Near'), ('F', 'From Followees')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
