version: "3.7"

services:
  db:
    image: kartoza/postgis:latest
    restart: always
    env_file:
      - .env
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASS=${POSTGRES_PASS}
    - POSTGRES_DBNAME=${POSTGRES_DBNAME}
    - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    volumes:
    - db-volume:/var/lib/postgresql
    ports:
    - ${EXPOSED_DATABASE_PORT}:${DATABASE_PORT}
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
    command: bash -c "chmod +x ./wait-for-it.sh && ./wait-for-it.sh db:${DATABASE_PORT} && python manage.py runsslserver 0.0.0.0:8000"
    volumes:
    - .:/code
    ports:
    - ${EXPOSED_APP_PORT}:8000
    depends_on:
      - db
volumes:
  db-volume: